"""
Pose Verifier Live (pose_verifier_live.py)
=========================================
Real-time Computer Vision and Biomechanical telemetry tool with OpenCV and MediaPipe.
Compares physical hand poses captured via webcam with the theoretical 3D pose
generated by HandKinematicsDirect (DADADADAFP taxonomy).

Features:
- Split-screen and overlay comparative modes.
- Real-time RMSE Euclidean error and joint angular telemetry.
- Dynamic color highlighting per joint (Green <10%, Yellow 10-25%, Red >25%).
- Canonical LIBRAS presets & custom 10-digit code input.
- Interactive 3D wireframe rotation via mouse drag.
- Diagnostic log export on key [S].
"""

import os
import sys
import time
import math
import json
from datetime import datetime
from typing import Dict, List, Tuple, Optional, Any

# --- Protobuf fix for MediaPipe on Windows ---
os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'

import cv2
import numpy as np
import mediapipe as mp

# Add current scripts directory to path
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS_DIR = os.path.join(BASE_DIR, 'scripts')
DATA_DIR = os.path.join(BASE_DIR, 'data')
DIAGNOSTICS_DIR = os.path.join(DATA_DIR, 'calibration_diagnostics')
os.makedirs(DIAGNOSTICS_DIR, exist_ok=True)

if SCRIPTS_DIR not in sys.path:
    sys.path.insert(0, SCRIPTS_DIR)

from kinematic_seed_generator import HandKinematicsDirect, rot_x, rot_y, rot_z


# ---------------------------------------------------------------------------
# COLOR PALETTES & GRAPHICAL CONSTANTS
# ---------------------------------------------------------------------------

FINGER_COLORS_BGR = {
    'Thumb':  (34, 87, 255),   # Orange-Red
    'Index':  (59, 235, 255),  # Yellow
    'Middle': (80, 175, 76),   # Green
    'Ring':   (212, 188, 0),   # Cyan
    'Pinky':  (176, 39, 156)   # Purple
}

FINGER_SEGMENTS = {
    'Thumb':  [(0, 1), (1, 2), (2, 3), (3, 4)],
    'Index':  [(0, 5), (5, 6), (6, 7), (7, 8)],
    'Middle': [(0, 9), (9, 10), (10, 11), (11, 12)],
    'Ring':   [(0, 13), (13, 14), (14, 15), (15, 16)],
    'Pinky':  [(0, 17), (17, 18), (18, 19), (19, 20)]
}

PALM_CONNECTIONS = [(0, 1), (0, 5), (0, 9), (0, 13), (0, 17), (5, 9), (9, 13), (13, 17)]

PRESET_POSES = [
    ("0000000000", "Mão Aberta Total (Estágio 0)"),
    ("1111111100", "Mão Garra / Relaxada (Estágio 1)"),
    ("2121212100", "Mão Plataforma (Estágio 2)"),
    ("3131313100", "Punho Fechado (Polegar Aberto)"),
    ("3131313111", "Sinal 'A' (Punho Fechado + Polegar Oposto)"),
    ("0101010100", "Sinal 'B' (Mão Espalmada com Dedos Unidos)"),
    ("0131313100", "Sinal 'I' (Apenas Mindinho Levantado)"),
    ("3131000000", "Sinal 'V' (Indicador e Médio em V)"),
    ("3100000000", "Sinal 'W' (Indicador, Médio e Anelar em W)"),
    ("3131310100", "Sinal 'L' (Indicador e Polegar a 90°)")
]


# ---------------------------------------------------------------------------
# POSE VERIFIER APPLICATION
# ---------------------------------------------------------------------------

class PoseVerifierLive:
    def __init__(self):
        self.kinematics = HandKinematicsDirect()
        self.preset_idx = 0
        self.current_code = PRESET_POSES[0][0]
        self.current_desc = PRESET_POSES[0][1]

        # Mode: 'split' or 'overlay'
        self.display_mode = 'split'

        # 3D View Camera Rotation (Orbit Yaw/Pitch)
        self.view_yaw = 0.0
        self.view_pitch = 0.0
        self.is_dragging = False
        self.drag_start_x = 0
        self.drag_start_y = 0

        # Custom Code Input Mode
        self.is_typing_code = False
        self.typed_code = ""

        # Notification message & timer
        self.notification_text = ""
        self.notification_expire = 0.0

        # Initialize MediaPipe Hands
        self.mp_hands = mp.solutions.hands
        self.hands = self.mp_hands.Hands(
            static_image_mode=False,
            max_num_hands=1,
            model_complexity=1,
            min_detection_confidence=0.6,
            min_tracking_confidence=0.5
        )

        # Expected landmarks cache
        self.cached_expected_lms = self.kinematics.build_landmarks_from_code(self.current_code)

    def set_code(self, code: str, desc: str = "Custom Code"):
        is_valid, reason = self.kinematics.is_valid_pose(code)
        if not is_valid:
            self.show_notification(f"Código Inválido: {reason}", duration=3.0)
            return False
        self.current_code = code
        self.current_desc = desc
        self.cached_expected_lms = self.kinematics.build_landmarks_from_code(code)
        self.show_notification(f"Pose Selecionada: [{code}] {desc}", duration=2.0)
        return True

    def show_notification(self, text: str, duration: float = 2.0):
        self.notification_text = text
        self.notification_expire = time.time() + duration

    def normalize_mediapipe_hand(self, raw_lms, is_left_hand: bool = False) -> np.ndarray:
        """
        Normalize raw MediaPipe hand landmarks:
        1. Anchor root (Wrist idx 0) at (0, 0, 0).
        2. If Left Hand, mirror along X-axis to match Right-Hand canonical space.
        3. Orient hand such that distal direction aligns with -Y.
        4. Scale so that Middle MCP length is normalized to standard 1.03.
        """
        pts = np.array([[lm.x, lm.y, lm.z] for lm in raw_lms], dtype=np.float64)

        # Mirror left hand
        if is_left_hand:
            pts[:, 0] = -pts[:, 0]

        # Anchor at Wrist
        pts_rel = pts - pts[0]

        # Scale relative to Middle MCP length (Standard = 1.03)
        middle_mcp_len = np.linalg.norm(pts_rel[9])
        if middle_mcp_len > 1e-5:
            scale_factor = 1.03 / middle_mcp_len
            pts_rel = pts_rel * scale_factor

        # In MediaPipe screen coords, Y points downwards (towards bottom of image)
        # In our kinematic model, proximal is at (0,0) and fingers extend towards -Y
        # If Middle MCP Y is positive in relative screen space, invert Y to match -Y distal
        if pts_rel[9, 1] > 0:
            pts_rel[:, 1] = -pts_rel[:, 1]

        return pts_rel

    def compute_telemetry_and_errors(self, real_lms: np.ndarray, expected_lms: np.ndarray) -> Dict[str, Any]:
        """
        Compute joint-by-joint Euclidean errors, RMSE, and angular telemetry.
        """
        # Per-landmark Euclidean error
        errors = np.linalg.norm(real_lms - expected_lms, axis=1)
        palm_ref_len = np.linalg.norm(expected_lms[9])  # 1.03
        norm_errors = errors / max(palm_ref_len, 1e-6)

        rmse = math.sqrt(np.mean(errors ** 2))

        # Color coding per joint: Green (<10%), Yellow (10-25%), Red (>25%)
        joint_colors = []
        for err_ratio in norm_errors:
            if err_ratio < 0.12:
                joint_colors.append((0, 255, 0))     # Green
            elif err_ratio < 0.28:
                joint_colors.append((0, 255, 255))   # Yellow
            else:
                joint_colors.append((0, 0, 255))     # Red

        # Finger-level error summary
        finger_errors = {
            'Thumb':  np.mean(norm_errors[1:5]),
            'Index':  np.mean(norm_errors[5:9]),
            'Middle': np.mean(norm_errors[9:13]),
            'Ring':   np.mean(norm_errors[13:17]),
            'Pinky':  np.mean(norm_errors[17:21])
        }

        return {
            'rmse': rmse,
            'norm_errors': norm_errors,
            'joint_colors': joint_colors,
            'finger_errors': finger_errors
        }

    def render_3d_wireframe(self, landmarks_3d: np.ndarray, width: int, height: int,
                            joint_colors: Optional[List[Tuple[int, int, int]]] = None) -> np.ndarray:
        """
        Render 3D hand skeleton into a 2D image buffer with interactive orbit rotation.
        """
        canvas = np.zeros((height, width, 3), dtype=np.uint8)
        canvas[:] = (20, 20, 28)  # Sleek dark background

        # Rotation matrix for 3D camera orbit
        R_view = rot_y(self.view_yaw).dot(rot_x(self.view_pitch))
        pts_rot = R_view.dot(landmarks_3d.T).T

        # Project 3D points to 2D screen coordinates
        center_x = width // 2
        center_y = height // 2 + int(height * 0.25)
        scale = min(width, height) * 0.38

        pts_2d = []
        for p in pts_rot:
            u = int(center_x + p[0] * scale)
            v = int(center_y + p[1] * scale)  # Y is negative distal
            pts_2d.append((u, v))

        # 1. Draw Palm Base Connections
        for start, end in PALM_CONNECTIONS:
            cv2.line(canvas, pts_2d[start], pts_2d[end], (85, 85, 110), 2, cv2.LINE_AA)

        # 2. Draw Finger Segments
        for finger, segs in FINGER_SEGMENTS.items():
            col = FINGER_COLORS_BGR[finger]
            for start, end in segs:
                cv2.line(canvas, pts_2d[start], pts_2d[end], col, 3, cv2.LINE_AA)

        # 3. Draw Landmark Nodes
        for i, (u, v) in enumerate(pts_2d):
            col = joint_colors[i] if joint_colors else (255, 255, 255)
            cv2.circle(canvas, (u, v), 6, (10, 10, 10), -1, cv2.LINE_AA)
            cv2.circle(canvas, (u, v), 4, col, -1, cv2.LINE_AA)

        # Draw Coordinate Axes Indicator at bottom-left
        ax_origin = (50, height - 50)
        ax_len = 30
        for axis_vec, col, label in [([1, 0, 0], (0, 0, 255), 'X'), ([0, -1, 0], (0, 255, 0), 'Y'), ([0, 0, 1], (255, 0, 0), 'Z')]:
            rot_ax = R_view.dot(np.array(axis_vec))
            ax_end = (int(ax_origin[0] + rot_ax[0] * ax_len), int(ax_origin[1] + rot_ax[1] * ax_len))
            cv2.line(canvas, ax_origin, ax_end, col, 2, cv2.LINE_AA)
            cv2.putText(canvas, label, (ax_end[0] + 4, ax_end[1] + 4), cv2.FONT_HERSHEY_SIMPLEX, 0.35, col, 1, cv2.LINE_AA)

        return canvas

    def save_diagnostic_log(self, real_lms: np.ndarray, expected_lms: np.ndarray, telemetry: Dict[str, Any]):
        """
        Save diagnostic JSON log containing real vs theoretical landmarks and telemetry.
        """
        timestamp_str = datetime.now().strftime("%Y%m%d_%H%M%S")
        filename = f"telemetry_{self.current_code}_{timestamp_str}.json"
        filepath = os.path.join(DIAGNOSTICS_DIR, filename)

        log_data = {
            "timestamp": timestamp_str,
            "taxonomy_code": self.current_code,
            "pose_description": self.current_desc,
            "metrics": {
                "rmse_euclidean": float(round(telemetry['rmse'], 5)),
                "finger_normalized_errors": {
                    k: float(round(v, 5)) for k, v in telemetry['finger_errors'].items()
                }
            },
            "real_landmarks_normalized": [
                {"idx": i, "x": float(round(p[0], 5)), "y": float(round(p[1], 5)), "z": float(round(p[2], 5))}
                for i, p in enumerate(real_lms)
            ],
            "expected_landmarks_3d": [
                {"idx": i, "x": float(round(p[0], 5)), "y": float(round(p[1], 5)), "z": float(round(p[2], 5))}
                for i, p in enumerate(expected_lms)
            ],
            "calibration_suggestions": {
                "thumb_opposition_adjustment": "Check thumb roll/pronation offset if Thumb error > 0.20",
                "mcp_flexion_adjustment": "Fine-tune J2 pitch stage mapping if Index/Middle error > 0.20"
            }
        }

        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(log_data, f, indent=2)

        self.show_notification(f"[S] Log Salvo: {filename}", duration=3.0)
        print(f"[PoseVerifierLive] Telemetry log saved: {filepath}")

    def on_mouse(self, event, x, y, flags, param):
        """Handle 3D view orbit dragging with mouse."""
        if event == cv2.EVENT_LBUTTONDOWN:
            self.is_dragging = True
            self.drag_start_x = x
            self.drag_start_y = y
        elif event == cv2.EVENT_MOUSEMOVE:
            if self.is_dragging:
                dx = x - self.drag_start_x
                dy = y - self.drag_start_y
                self.view_yaw += dx * 0.6
                self.view_pitch += dy * 0.6
                self.drag_start_x = x
                self.drag_start_y = y
        elif event == cv2.EVENT_LBUTTONUP:
            self.is_dragging = False

    def draw_telemetry_hud(self, panel: np.ndarray, telemetry: Optional[Dict[str, Any]]):
        """Draw modern HUD with metrics, telemetry table, and shortcuts."""
        h, w = panel.shape[:2]

        # Top Banner
        cv2.rectangle(panel, (0, 0), (w, 75), (15, 15, 22), -1)
        cv2.line(panel, (0, 75), (w, 75), (50, 50, 70), 1)

        cv2.putText(panel, f"POSE: [{self.current_code}]", (15, 30),
                    cv2.FONT_HERSHEY_DUPLEX, 0.75, (255, 255, 255), 1, cv2.LINE_AA)
        cv2.putText(panel, self.current_desc, (15, 58),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.45, (180, 180, 210), 1, cv2.LINE_AA)

        # Telemetry Card
        card_y = 85
        card_h = 175
        cv2.rectangle(panel, (10, card_y), (w - 10, card_y + card_h), (25, 25, 35), -1)
        cv2.rectangle(panel, (10, card_y), (w - 10, card_y + card_h), (55, 55, 75), 1)

        cv2.putText(panel, "TELEMETRIA DE ERRO (REAL vs ESPERADO)", (20, card_y + 22),
                    cv2.FONT_HERSHEY_DUPLEX, 0.45, (137, 180, 250), 1, cv2.LINE_AA)

        if telemetry:
            rmse = telemetry['rmse']
            score_pct = max(0.0, min(100.0, (1.0 - (rmse / 0.6)) * 100.0))
            score_col = (0, 255, 0) if score_pct > 75 else ((0, 255, 255) if score_pct > 50 else (0, 0, 255))

            cv2.putText(panel, f"RMSE: {rmse:.3f} | CONFORMIDADE: {score_pct:.1f}%", (20, card_y + 48),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.5, score_col, 1, cv2.LINE_AA)

            # Per-finger bar charts
            row_y = card_y + 70
            for finger in ['Thumb', 'Index', 'Middle', 'Ring', 'Pinky']:
                err_val = telemetry['finger_errors'][finger]
                bar_len = int(min(120, err_val * 250))
                bar_col = (0, 255, 0) if err_val < 0.12 else ((0, 255, 255) if err_val < 0.28 else (0, 0, 255))

                cv2.putText(panel, f"{finger[:3]}:", (20, row_y + 12),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.42, (200, 200, 220), 1, cv2.LINE_AA)
                cv2.rectangle(panel, (75, row_y + 3), (75 + 120, row_y + 13), (40, 40, 50), -1)
                cv2.rectangle(panel, (75, row_y + 3), (75 + bar_len, row_y + 13), bar_col, -1)
                cv2.putText(panel, f"{err_val*100:.1f}%", (205, row_y + 12),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.4, (200, 200, 220), 1, cv2.LINE_AA)
                row_y += 20
        else:
            cv2.putText(panel, "Aguardando deteccao de mao na camera...", (20, card_y + 80),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (120, 120, 150), 1, cv2.LINE_AA)

        # Shortcuts / Help Box at Bottom
        help_y = h - 110
        cv2.rectangle(panel, (10, help_y), (w - 10, h - 10), (15, 15, 22), -1)
        cv2.rectangle(panel, (10, help_y), (w - 10, h - 10), (45, 45, 60), 1)

        shortcuts = [
            "[0-9]/[TAB]: Mudar Pose",
            "[M]: Modo Split/Overlay",
            "[S]: Salvar Log JSON",
            "[R]: Resetar Visao 3D",
            "[C]: Digitar Codigo 10 Digitos",
            "[ESC/Q]: Sair"
        ]
        cv2.putText(panel, "ATALHOS:", (20, help_y + 18), cv2.FONT_HERSHEY_SIMPLEX, 0.4, (137, 180, 250), 1, cv2.LINE_AA)
        for i, text in enumerate(shortcuts):
            col_idx = i % 2
            row_idx = i // 2
            x_pos = 20 + col_idx * 160
            y_pos = help_y + 38 + row_idx * 20
            cv2.putText(panel, text, (x_pos, y_pos), cv2.FONT_HERSHEY_SIMPLEX, 0.35, (160, 160, 180), 1, cv2.LINE_AA)

        # Draw Notification Toast if active
        if time.time() < self.notification_expire and self.notification_text:
            toast_w = min(w - 40, len(self.notification_text) * 11 + 30)
            toast_x = (w - toast_w) // 2
            toast_y = h - 145
            cv2.rectangle(panel, (toast_x, toast_y), (toast_x + toast_w, toast_y + 32), (0, 140, 255), -1)
            cv2.putText(panel, self.notification_text, (toast_x + 12, toast_y + 22),
                        cv2.FONT_HERSHEY_SIMPLEX, 0.45, (255, 255, 255), 1, cv2.LINE_AA)

    def run(self):
        print("\n===================================================================")
        print("   LIBRAS POSE VERIFIER LIVE (3D KINEMATICS vs WEBCAM CV)         ")
        print("===================================================================")
        print(" Controles:")
        print("  - Teclas [0-9] ou [TAB] : Alternar poses predefinidas (A, B, I, V, W, etc.)")
        print("  - Tecla [M]             : Alternar modo Split-Screen / Overlay")
        print("  - Tecla [S]             : Salvar log de telemetria / calibracao em JSON")
        print("  - Tecla [R]             : Resetar angulo de rotacao da camera 3D")
        print("  - Tecla [C]             : Digitar codigo DADADADAFP customizado no terminal")
        print("  - Arraste do Mouse      : Rotacionar esqueleto 3D no espaco")
        print("  - Tecla [Q] ou [ESC]    : Sair")
        print("===================================================================\n")

        cap = cv2.VideoCapture(0)
        window_name = "LIBRAS Pose Verifier Live (MediaPipe vs 3D Kinematics)"
        cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
        cv2.setMouseCallback(window_name, self.on_mouse)

        # Fallback dummy frame if webcam fails
        camera_available = cap.isOpened()
        if not camera_available:
            print("[AVISO] Webcam fisica nao detectada. Executando em modo de simulacao sintetica.")

        fps_timer = time.time()
        frame_count = 0
        fps = 0.0

        try:
            while True:
                if camera_available:
                    ret, frame = cap.read()
                    if not ret:
                        frame = np.zeros((480, 640, 3), dtype=np.uint8)
                    else:
                        frame = cv2.flip(frame, 1)  # Mirror view
                else:
                    frame = np.zeros((480, 640, 3), dtype=np.uint8)
                    cv2.putText(frame, "Webcam Indisponivel (Modo Simulacao 3D)", (50, 240),
                                cv2.FONT_HERSHEY_SIMPLEX, 0.6, (100, 100, 255), 1, cv2.LINE_AA)

                h_cam, w_cam = frame.shape[:2]
                frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
                results = self.hands.process(frame_rgb)

                telemetry = None
                real_normalized_lms = None
                joint_colors = None

                if results.multi_hand_landmarks:
                    hand_lms = results.multi_hand_landmarks[0]
                    is_left = False
                    if results.multi_handedness:
                        label = results.multi_handedness[0].classification[0].label
                        is_left = (label == 'Left')

                    # 1. Normalize real landmarks
                    real_normalized_lms = self.normalize_mediapipe_hand(hand_lms.landmark, is_left_hand=is_left)

                    # 2. Compute Telemetry against current expected pose
                    telemetry = self.compute_telemetry_and_errors(real_normalized_lms, self.cached_expected_lms)
                    joint_colors = telemetry['joint_colors']

                    # 3. Draw colored landmarks on webcam frame
                    for i, lm in enumerate(hand_lms.landmark):
                        cx, cy = int(lm.x * w_cam), int(lm.y * h_cam)
                        col = joint_colors[i]
                        cv2.circle(frame, (cx, cy), 6, col, -1, cv2.LINE_AA)
                        cv2.circle(frame, (cx, cy), 7, (0, 0, 0), 1, cv2.LINE_AA)

                    # Draw basic connections
                    for start, end in PALM_CONNECTIONS:
                        pt1 = (int(hand_lms.landmark[start].x * w_cam), int(hand_lms.landmark[start].y * h_cam))
                        pt2 = (int(hand_lms.landmark[end].x * w_cam), int(hand_lms.landmark[end].y * h_cam))
                        cv2.line(frame, pt1, pt2, (180, 180, 180), 1, cv2.LINE_AA)

                    for finger, segs in FINGER_SEGMENTS.items():
                        col = FINGER_COLORS_BGR[finger]
                        for start, end in segs:
                            pt1 = (int(hand_lms.landmark[start].x * w_cam), int(hand_lms.landmark[start].y * h_cam))
                            pt2 = (int(hand_lms.landmark[end].x * w_cam), int(hand_lms.landmark[end].y * h_cam))
                            cv2.line(frame, pt1, pt2, col, 2, cv2.LINE_AA)

                # 4. Render Expected 3D Wireframe
                wireframe_panel = self.render_3d_wireframe(self.cached_expected_lms, w_cam, h_cam, joint_colors)
                self.draw_telemetry_hud(wireframe_panel, telemetry)

                # 5. Composite Screen (Split or Overlay)
                if self.display_mode == 'split':
                    composite = np.hstack((frame, wireframe_panel))
                else:
                    # Overlay Mode
                    alpha = 0.55
                    composite = cv2.addWeighted(frame, 1.0 - alpha, wireframe_panel, alpha, 0)

                # FPS Counter
                frame_count += 1
                if time.time() - fps_timer >= 1.0:
                    fps = frame_count / (time.time() - fps_timer)
                    frame_count = 0
                    fps_timer = time.time()

                cv2.putText(composite, f"FPS: {fps:.1f}", (15, h_cam - 15),
                            cv2.FONT_HERSHEY_SIMPLEX, 0.45, (0, 255, 0), 1, cv2.LINE_AA)

                cv2.imshow(window_name, composite)

                # Handle Key Events
                key = cv2.waitKey(1) & 0xFF
                if key in [ord('q'), ord('Q'), 27]:  # 27 = ESC
                    break
                elif key == 9 or key == ord('n') or key == ord('N'):  # TAB or N = Next Preset
                    self.preset_idx = (self.preset_idx + 1) % len(PRESET_POSES)
                    code, desc = PRESET_POSES[self.preset_idx]
                    self.set_code(code, desc)
                elif key == ord('p') or key == ord('P'):  # P = Previous Preset
                    self.preset_idx = (self.preset_idx - 1) % len(PRESET_POSES)
                    code, desc = PRESET_POSES[self.preset_idx]
                    self.set_code(code, desc)
                elif ord('0') <= key <= ord('9'):
                    idx = key - ord('0')
                    if idx < len(PRESET_POSES):
                        self.preset_idx = idx
                        code, desc = PRESET_POSES[idx]
                        self.set_code(code, desc)
                elif key in [ord('m'), ord('M')]:
                    self.display_mode = 'overlay' if self.display_mode == 'split' else 'split'
                    self.show_notification(f"Modo: {self.display_mode.upper()}", duration=1.5)
                elif key in [ord('r'), ord('R')]:
                    self.view_yaw = 0.0
                    self.view_pitch = 0.0
                    self.show_notification("Visao 3D Resetada", duration=1.5)
                elif key in [ord('s'), ord('S')]:
                    if real_normalized_lms is not None and telemetry is not None:
                        self.save_diagnostic_log(real_normalized_lms, self.cached_expected_lms, telemetry)
                    else:
                        self.show_notification("[!] Mostre sua mao na camera para salvar o log.", duration=2.5)
                elif key in [ord('c'), ord('C')]:
                    print("\n[Input] Digite o codigo de 10 digitos da taxonomia DADADADAFP (ex: 3131313111): ")
                    custom_code = input(">> ").strip()
                    if custom_code:
                        self.set_code(custom_code, "Pose Personalizada")

        finally:
            if camera_available:
                cap.release()
            cv2.destroyAllWindows()
            self.hands.close()
            print("[PoseVerifierLive] Encerrado com sucesso.")


def main():
    app = PoseVerifierLive()
    app.run()


if __name__ == "__main__":
    main()
